import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import WeatherCard from "../components/WeatherCard";
import nookies from "nookies";
import { http } from "./api/http";
import { deleteCookies } from "../lib/session";
import { useRouter } from "next/router";
import { message } from "antd";

function Home(ctx) {
  const router = useRouter();
  const [messageApi, contextHolder] = message.useMessage();

  const handleLogout = async () => {
    await deleteCookies();
    router.reload();
    messageApi.open({
      type: "warning",
      content: "Your session has ended.",
    });
  };

  const Divider = () => {
    return <div className={styles.divider}></div>;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Xplore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.nav}>
          <h2>Xplore</h2>
          <div className={styles.navSessionContainer}>
            {ctx?.props?.username ? (
              <>
                <p>{ctx?.props?.username}</p>
                <button className={styles.navButton} onClick={handleLogout}>
                  Logout
                </button>
              </>
            ) : (
              <button
                className={styles.navButton}
                onClick={() => router.push("/login")}
              >
                Login
              </button>
            )}
          </div>
        </div>
        <div className={styles.hero_container}>
          <section className={styles.leftSection}>
            <h1>Travel assistance</h1>
            <p>
              Liberte o explorador dentro de você e descubra os destinos mais
              encantadores do mundo.
            </p>
            <div>
              <input placeholder="pesquisar por cidade, ex: Maputo" />
              <button>Pesquisar</button>
            </div>
          </section>
          <section className={styles.rightSection}>
            <WeatherCard />
            <WeatherCard />
            <WeatherCard />
          </section>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by paichato
        </a>
      </footer>
    </div>
  );
}

Home.getInitialProps = async (ctx) => {
  const { "xplore.token": token } = nookies.get(ctx);

  if (!token) return { props: { user: null } };

  const response = await http
    .get("/validate-user", { headers: { Authorization: `Bearer ${token}` } })
    .then((res) => {
      http.defaults.headers.common["Authorization"] = token;

      res.data.session = "active";

      return res.data;
    })
    .catch((err) => {});

  if (!response) return { props: { username: null } };
  return { props: response };
};

export default Home;
